---

- hosts: localhost
  vars_files: 
    - vars/main.yml
  tasks:
    - name: Spin up miners on Vultr
      community.general.terraform:
        project_path: ./terraform
        state: present
        variables:
          instance_count: "{{ instance_count }}"
    - meta: refresh_inventory


# The insanity54.base role sets up the VPS
# for working with Ansible.
# It requires that we do not gather_facts.
- hosts: miners
  gather_facts: no
  roles:
    - role: insanity54.base

- hosts: miners
  vars_files: 
    - vars/main.yml
  roles:
    - role: insanity54.pkt

